[[exercises]]
title = "Question 16 in Fall 2021 Final Exam"
difficulty = "Intermediate"
table = false
type = "explaination"
multipart= true

question = """
For each code snippet, specify the worst case complexity using the Big-O notation. 

```{code-block} cpp
for (int i = 0; i < n; i++) {
  for (int j = 0; j * j < n; j++) {
    // some code with o(1)
  }
}
```
"""

answer = """
Think of it as $n \\times (j^2 < n \\rightarrow j < \\sqrt{n} = ) \\sqrt{n} = n^\\frac{3}{2}$

$O(n^\\frac{3}{2})$
"""

[[exercises]]
title = "Question 16 in Fall 2021 Final Exam"
difficulty = "Intermediate"
table = false
type = "explaination"
multipart= true

question = """
```{code-block} cpp
for (int i = 0; i < n; i++) {
  for (int j = 0; j * j < 1000000; j++) {
    // some code with O(1)
  }
}
```
"""

answer = """
Think of it as $n \\times 1000000 = n$

$O(n)$
"""

[[exercises]]
title = "Question 16 in Fall 2021 Final Exam"
difficulty = "Intermediate"
table = false
type = "explaination"
multipart= true

question = """
```{code-block} cpp
for(int i = 1; i < n ; i = i*2){
  for(int j = 0; j < n; j++){
    // some code with O(1)
  }
}
```
"""

answer = """
The outer loop goes from 1, 2, 4, 8, 16 ...

To reach $n$, this takes $\\log(n)$ steps.

Think of it as $\\log(n) \\times n$

$O(n\\log(n))$
"""

[[exercises]]
title = "Question 17 in Fall 2021 Final Exam"
difficulty = "Intermediate"
table = false
type = "multiple-choice"
multipart= true

question = """
Two students were asked to write a recursive function that given a positive integer `n`, computes $2^n$. Amy wrote the following function:

```{code-block} cpp
int Amy(int n) {
  if (n == 0) {
    return 1;
  } else {
    return Amy(n - 1) + Amy(n - 1);
  }
}
```

John wrote the following function:

```{code-block} cpp
int John(int n) {
  if (n == 0) {
    return 1;
  } else {
    return (2 * John(n - 1));
  }
}
```

Answer the following question about code written by Amy and John.

(1) Is Amy's function correct (does it compute and return $2^n$)?
"""

answer = [0]

choices = [
  "Yes",
  "No"
]

explanations = ["Yes"]



[[exercises]]
title = "Question 17 in Fall 2021 Final Exam"
difficulty = "Intermediate"
table = false
type = "multiple-choice"
multipart= true

question = """
(2) Is John's function correct (does it compute and return $2^n$)?
"""

answer = [0]

choices = [
  "Yes",
  "No"
]

explanations = ["Yes"]



[[exercises]]
title = "Question 17 in Fall 2021 Final Exam"
difficulty = "Intermediate"
table = false
type = "explaination"
multipart= true

question = """
(3) What is the worst-case complexity of Amy's function using Big-O notation?
"""

answer = """
$O(2^n)$
"""

[[exercises]]
title = "Question 17 in Fall 2021 Final Exam"
difficulty = "Intermediate"
table = false
type = "explaination"
multipart= true

question = """
(4) What is the worst-case complexity of John's function using Big-O notation?
"""

answer = """
$T(n) = T(n - 1) + c$

$T(n) = T(n - 2) + 2c$

$O(n)$
"""


